dotnetuz-intership/BelissimoCloneWpf

BelissimoCloneWPF.Domain/Entities/Users/User.cs, BelissimoCloneWPF.Domain/Enums/UserRole.cs
I have created User class within 'Entities' folder.
=> Created User class within 'Entities' folder.

BellissimoCloneWPF.Data/BellissimoCloneWPF.Data.csproj
Created BellissimoCloneWpf.Data and Folders in it
=> Created BellissimoCloneWpf.Data and Folders in it

BelissimoCloneWPF.Domain/Entities/Foods/Category.cs, BelissimoCloneWPF.Domain/Entities/Foods/Food.cs
I have changed simple classes to sealed classes
=> I have changed simple classes to sealed classes 

BelissimoCloneWPF.Data/BelissimoCloneWPF.Data.csproj, BelissimoCloneWPF.sln, BellissimoCloneWPF.Data/BellissimoCloneWPF.Data.csproj
Create BillissimoCloneWPF.Data in it
=> Create BillissimoCloneWPF.Data in it

BelissimoCloneWPF.Domain/Entities/Baskets/Basket.cs, BelissimoCloneWPF.Domain/Entities/FoodOrders/FoodOrder.cs, BelissimoCloneWPF.Domain/Entities/Orders/FoodOrder.cs, BelissimoCloneWPF.Domain/Entities/Orders/Order.cs, BelissimoCloneWPF.Domain/Entities/Users/User.cs, BelissimoCloneWPF.Domain/Enums/OrderType.cs, BelissimoCloneWPF.Domain/Enums/PaymentType.cs
I created FoodOrder and Order classes with needable enum Classes.
=> Created Orders and FoodOrders with needable Enums.

BelissimoCloneWPF.Domain/Entities/Attachments/Attachments.cs
Domain: Attachment class created at the Entities foldier
=> Domain: Attachments created 

BelissimoCloneWPF.Domain/Entities/Attachment/Attachments.cs, BelissimoCloneWPF.Domain/Entities/Baskets/Basket.cs, BelissimoCloneWPF.Domain/Entities/Foods/Category.cs, BelissimoCloneWPF.Domain/Entities/Foods/Food.cs, BelissimoCloneWPF.Domain/Entities/Orders/FoodOrder.cs, BelissimoCloneWPF.Domain/Entities/Orders/Order.cs, BelissimoCloneWPF.Domain/Entities/Users/User.cs, BelissimoCloneWPF.sln
Added new property witihin this classes.
=> changed User, FoodOrder, Order, Basket classes.

BelissimoCloneWPF.Data/BelissimoCloneWPF.Data.csproj, BelissimoCloneWPF.Data/IRepositories/IGenericRepository.cs
Created IGenericRepository Interface Inside IRepositories Folder.
=> DATA: Created IGenericRepository Interface.

BelissimoCloneWPF.Service/BelissimoCloneWPF.Service.csproj, BelissimoCloneWPF.Service/DTOs/Foods/FoodForCreationDTO.cs
Service: Add New Foods Folder And Create FoodForCreationDto class
=> Service: Add New Foods Folder And Create FoodForCreationDto class

BelissimoCloneWPF.Service/DTOs/Category/CategoryForCreationDTO.cs
I have created CategoryForCreationDTO is that correct? #41
=> Service: CategoryForCreationgDTO created. 

BelissimoCloneWPF.Service/DTOs/Branches/BranchForCreationDTO.cs
=> SERVICES: BranchForCreationDTO successfully created in DTOs/Branches folder

BelissimoCloneWPF.Data/BelissimoCloneWPF.Data.csproj, BelissimoCloneWPF.Data/Contexts/BelissimoDbContext.cs, BelissimoCloneWPF.Data/DbContexts/BelissimoDbContext.cs, BelissimoCloneWPF.Domain/BelissimoCloneWPF.Domain.csproj, BelissimoCloneWPF.Domain/Enums/OrderType.cs, BelissimoCloneWPF.Domain/Enums/PaymentType.cs, BelissimoCloneWPF.Domain/Enums/UserRole.cs, BelissimoCloneWPF.Service/BelissimoCloneWPF.Service.csproj, BelissimoCloneWPF/BelissimoCloneWPF.csproj
I have created DbContext Folder and Created BelissimoContextDb class inside the folder and installed necessary packages.
Closed #36
=> Data: Created DbContext Folder and class within it

BelissimoCloneWPF.Data/Contexts/BelissimoDbContext.cs, BelissimoCloneWPF.Service/BelissimoCloneWPF.Service.csproj, BelissimoCloneWPF.Service/DTOs/FoodOrders/FoodOrderForCreationDTO.cs
Create FoodOrderForCreationDTO in Service layer!
Closes #45
=> SERVICE : Created FoodOrderForCreationDTO in Service layer

BelissimoCloneWPF.Domain/Configurations/PaginationParams.cs, BelissimoCloneWPF.Service/DTOs/Baskets/BasketForCreationDTO.cs
=> DOMAIN; SERVICE: Created BasketForCreationDTO and PaginationParam

BelissimoCloneWPF.Data/BelissimoCloneWPF.Data.csproj, BelissimoCloneWPF.Service/DTOs/Attachment/AttachmentForCreationDTO.cs, BelissimoCloneWPF.Service/DTOs/Foods/CategoryForCreationDTO.cs
successfully created  
Closes #52
=> Service: AttachmentForCreationDTO created

BelissimoCloneWPF.Service/Extentions/CollectionExtentions.cs
I have created ToPagedList static method in CollectionExtentions class in Extentions folder in Service Layer.
Closes #58
=> SERVICE: Created CollectionExtentions class inside Extentions folder

BelissimoCloneWPF.Data/BelissimoCloneWPF.Data.csproj, BelissimoCloneWPF.Data/Repositories/GenericRepository.cs
DATA: Corrected GenericRepository Class
=> DATA: Corrected GenericRepository Class

BelissimoCloneWPF.Service/BelissimoCloneWPF.Service.csproj, BelissimoCloneWPF.Service/Mappers/MappingProfile.cs
SERVICE: Created MappingProfile class in Mappers folder
=> SERVICE: Created MappingProfile class in Mappers folder

BelissimoCloneWPF.Service/Attributes/UserPassword.cs
=> SERVICE: Attributes folder and inside it UserPassword class created. #65

BelissimoCloneWPF.Data/Repositories/GenericRepository.cs, BelissimoCloneWPF.Service/Attributes/FormFileAttributes.cs, BelissimoCloneWPF.Service/BelissimoCloneWPF.Service.csproj, BelissimoCloneWPF.Service/Extentions/CollectionExtentions.cs
I have Created FormFileAttributes Class in Service/Attributes.
Closes #70
=> SERVICE: Created FormFileAttributes Class in Attributes folder

BelissimoCloneWPF.Service/Helpers/EnvironmentHelper.cs
=> SERVICE : Created EnvironmentHelper Class In Service

BelissimoCloneWPF.Data/IRepositories/IGenericRepository.cs
=> DATA: Add SaveChangesAsync method in IGenericRepository

BelissimoCloneWPF.Service/Attributes/UserLogin.cs
=> SERVICE : Create UserLogin Attribute

BelissimoCloneWPF.Service/BelissimoCloneWPF.Service.csproj, BelissimoCloneWPF.Service/DTOs/FoodOrders/FoodOrderForUpdateDTO.cs, BelissimoCloneWPF.Service/DTOs/FoodOrders/FoodOrderForViewDTO.cs, BelissimoCloneWPF.Service/Interfaces/FoodOrders/IFoodOrderService.cs, BelissimoCloneWPF.Service/Services/FoodOrders/FoodOrderService.cs
=> SERVICE : Create IFoodOrderService Interface And FoodOrderServie Class

BelissimoCloneWPF.Data/BelissimoCloneWPF.Data.csproj, BelissimoCloneWPF.Data/IRepositories/IGenericRepository.cs, BelissimoCloneWPF.Data/Repositories/GenericRepository.cs, BelissimoCloneWPF.Domain/BelissimoCloneWPF.Domain.csproj, BelissimoCloneWPF.Domain/Entities/Foods/Category.cs, BelissimoCloneWPF.Service/Attributes/FormFileAttributes.cs, BelissimoCloneWPF.Service/Attributes/UserLogin.cs, BelissimoCloneWPF.Service/Attributes/UserPassword.cs, BelissimoCloneWPF.Service/BelissimoCloneWPF.Service.csproj, BelissimoCloneWPF.Service/DTOs/Attachment/AttachmentForCreationDTO.cs, BelissimoCloneWPF.Service/DTOs/Foods/FoodForViewDTO.cs, BelissimoCloneWPF.Service/DTOs/Orders/OrderForCreationDTO.cs, BelissimoCloneWPF.Service/Exceptions/BelissimoCloneWPFException.cs, BelissimoCloneWPF.Service/Extentions/CollectionExtentions.cs, BelissimoCloneWPF.Service/Helpers/EnvironmentHelper.cs, BelissimoCloneWPF.Service/Helpers/HttpContextHelpers.cs, BelissimoCloneWPF.Service/Interfaces/FoodOrders/IFoodOrderService.cs, BelissimoCloneWPF.Service/Interfaces/Foods/IFoodService.cs, BelissimoCloneWPF.Service/Interfaces/Users/IUserService.cs, BelissimoCloneWPF.Service/Services/FoodOrders/FoodOrderService.cs, BelissimoCloneWPF.Service/Services/Foods/FoodService.cs, BelissimoCloneWPF/BelissimoCloneWPF.csproj
=> SERVICE: created FoodForCreationDTO, IFoodService and FoodService

BelissimoCloneWPF.Domain/Entities/Users/User.cs, BelissimoCloneWPF.Service/BelissimoCloneWPF.Service.csproj, BelissimoCloneWPF.Service/DTOs/Users/UserForLoginDTO.cs, BelissimoCloneWPF.Service/Interfaces/Users/IAuthService.cs, BelissimoCloneWPF.Service/Services/Users/AuthService.cs
=> SERIVCE : Create IAuthService and AuthService

BelissimoCloneWPF.Service/Interfaces/Attachment/IAttachmentService.cs, BelissimoCloneWPF.Service/Services/Attachment/AttachmentService.cs
=> SERVICE: Created interface IAttachmentService and class AttachmentService

BelissimoCloneWPF/MainWindow.xaml, BelissimoCloneWPF/MainWindow.xaml.cs
=> WPF: Create Category Buttons and Basket Button and Address Button

BelissimoCloneWPF/FoodController.xaml
=> WPF:  FoodControllect, Border And TextBlock Added
